export { default as Navbar } from '/src/components/Navbar/index'
export { default as Profile } from '/src/components/Profile/index'
export { default as Movies } from '/src/components/Movies/index'
export { default as MovieInformation } from '/src/components/MovieInformation/index'
export { default as Actors } from '/src/components/Actors/index'
